[package]
name = "defmt-stdout"
version = "0.1.2"
edition = "2024"
description = "Transmit defmt log messages to the standard output (Linux only)"
readme = "README.md"
repository = "https://github.com/SakiiCode/defmt-stdout"
license = "MIT"
keywords = ["defmt", "simulator", "stdout"]
categories = ["command-line-interface", "embedded", "simulation"]

[lib]
doctest = false
path = "src/lib.rs"

[dependencies]
defmt = "1.0.1"

[dev-dependencies]
assert_cmd = "2.1.2"
